---
title: "Mutations"
author: "Sushil Sudhakar"
date: "10/25/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("ape")
#install.packages("nlme")
#install.packages("rms")
#install.packages("phytools")
#install.packages("geiger")
#install.packages("caper")
#install.packages("tidyverse")
#install.packages("cowplot")
#install.packages("ggrepel")
#install.packages("ggsci")
#install.packages("patchwork")
library(ape)
library(nlme)
library(rms)
library(phytools)
library(geiger)
library(caper)
library(tidyverse)
library(cowplot)
library(ggrepel)
library(ggsci)
library(patchwork)
```

```{r}
modPgls.SEy = function (model, data, corClass = corBrownian, tree, se = NULL, 
                        method = c("REML", "ML"), interval = c(0, 1000), corClassValue=1, sig2e=NULL, ...) 
{
  Call <- match.call()
  corfunc <- corClass
  spp <- rownames(data)
  data <- cbind(data, spp)
  if (is.null(se)) 
    se <- setNames(rep(0, Ntip(tree)), tree$tip.label)[spp]
  else se <- se[spp]
  
  lk <- function(sig2e, data, tree, model, ve, corfunc, spp) {
    tree$edge.length <- tree$edge.length * sig2e
    ii <- sapply(1:Ntip(tree), function(x, e) which(e == 
                                                      x), e = tree$edge[, 2])
    tree$edge.length[ii] <- tree$edge.length[ii] + ve[tree$tip.label]
    vf <- diag(vcv(tree))[spp]
    w <- varFixed(~vf)
    COR <- corfunc(corClassValue, tree, form = ~spp, ...)
    fit <- gls(model, data = cbind(data, vf), correlation = COR, 
               method = method, weights = w)
    -logLik(fit)
  }
  
  if (is.null(sig2e)) {
    fit <- optimize(lk, interval = interval, data = data, tree = tree, 
                    model = model, ve = se^2, corfunc = corfunc, spp = spp)
    sig2e=fit$minimum
  }
  
  tree$edge.length <- tree$edge.length * sig2e
  ii <- sapply(1:Ntip(tree), function(x, e) which(e == x), 
               e = tree$edge[, 2])
  tree$edge.length[ii] <- tree$edge.length[ii] + se[tree$tip.label]^2
  vf <- diag(vcv(tree))[spp]
  w <- varFixed(~vf)
  obj <- gls(model, data = cbind(data, vf), correlation = corfunc(corClassValue, 
                                                                  tree, form = ~spp, ...), weights = w, method = method)
  obj$call <- Call
  obj$sig2e <- sig2e
  obj
}

#Internal function
pglsSEyPagelToOptimizeLambda=function(lambda,model,data,tree,...) {
  -logLik(modPgls.SEy(model=model,data=data,tree=tree,corClassValue=lambda,corClass=corPagel,fixed=T,...)) #Returns -logLikelihood of the pgls.SEy model with lambda fixed to the value of the lambda argument. sig2e will be optimized within modPgls.SEy unless given as an argument here
}

#Function intended for users
pglsSEyPagel=function(model, data, tree, lambdaInterval=c(0,1),...){
  optimizedModel=optimize(pglsSEyPagelToOptimizeLambda,lambdaInterval,model=model,data=data,tree=tree,...) #Optimizes lambda in the lambdaInterval using the pglsSEyPagelToOptimizeLambda function
  return(modPgls.SEy(model=model,data=data,tree=tree,corClass=corPagel,fixed=T,corClassValue=optimizedModel$minimum,...)) #Returns the final model fit
}
```

```{r}
Data <- read.csv("Mutation_Data.csv")
tree <- read.tree("min20Fixed516.nwk")
View(Data)
```


this code takes in the .nwk file i sent and prunes the phylogeny so that it matches your dataset.
```{r}
Data$Species <- gsub(" ", "_", Data$Species) 
Data$common_name<-gsub("_", "", Data$common_name)
includedSpecies<-Data$Species
pruned.tree<-drop.tip(
  tree, setdiff(
    tree$tip.label, includedSpecies))
pruned.tree <- keep.tip(pruned.tree,pruned.tree$tip.label)
Data$Keep <- Data$Species %in% pruned.tree$tip.label
Data <- Data[!(Data$Keep==FALSE),]
rownames(Data)<-Data$Species
SE<-setNames(Data$SE_simple,Data$Species)[rownames(Data)]
```

Construct the Regression Model    
```{r}
mutation.neo<-pglsSEyPagel(NeoplasiaPrevalence~log10(Mean.mutation.rate..SBS.genome.year.),data=Data,tree=pruned.tree,se=SE,method = "ML")
```

```{r}
summary(mutation.neo) 
###the code below extracts the stats from the above model to be used to construct the regression graph
r.v.mutation.neo <- summary(mutation.neo)$corBeta
r.v.mutation.neo <- format(r.v.mutation.neo[2,1])
r.v.mutation.neo <-signif(as.numeric(r.v.mutation.neo)^2, digits= 2)
ld.v.mutation.neo<- summary(mutation.neo)$modelStruct$corStruct
ld.v.mutation.neo <- signif(ld.v.mutation.neo[1], digits = 2)
p.v.mutation.neo<-summary(mutation.neo)$tTable
p.v.mutation.neo<-signif(p.v.mutation.neo[2,4], digits = 2)
```

```{r}
mutation.neo<-ggplot(Data, aes(y=NeoplasiaPrevalence*100, x=log10(Mean.mutation.rate..SBS.genome.year.)))+
  ## I *think* that we only have mutation for Mammalia so you may need to change the line below
  scale_color_manual(values = c("Mammalia" = "#631879FF"))+
  scale_y_continuous(
    limits = c(0,75),
    breaks = c(0, 25,50,75),
    labels = c(0, 25,50,75))+
  geom_abline(intercept = coef(mutation.neo)[1]*100, slope =  coef(mutation.neo)[2]*100,
              color = 'grey',size = 1.2) +
  theme_cowplot(12)+
  theme(axis.title = element_text(size = 18))+
  ylab("Neoplasia Prevalence (%)") +
  xlab("(log10) Mutation Rate") +
  geom_point(aes(colour= Clade, size = RecordsWithDenominators)) +
  scale_size(name   = "Total Necropsies",
             breaks = c(20,100,200,300,477),
             labels =  c(20,100,200,300,477))+
  geom_text_repel(aes(label=ifelse( NeoplasiaPrevalence > 0,as.character(common_name),'')),max.overlaps = Inf,size=5, direction = "y")+
  guides(colour = guide_legend(override.aes = list(size=3))) +
  labs(title = "A")+
  theme(
    plot.title = element_text(size = 20, face = "bold")) +
  theme(legend.position = "bottom")+
  labs(colour="Clade", size="Total Necropsies")
mutation.neo
##this line will save the graph to the folder you are using as your working directory
ggsave(filename='mutation.neo.pdf', width=9.5, height=7, limitsize=FALSE,bg="white")
```
Construct the Regression Model  Malignancy  
```{r}
mutation.mal<-pglsSEyPagel(MalignancyPrevalence~log10(Mean.mutation.rate..SBS.genome.year.),data=Data,tree=pruned.tree,se=SE,method = "ML")
```


```{r}
summary(mutation.mal) 
###the code below extracts the stats from the above model to be used to construct the regression graph
r.v.mutation.mal <- summary(mutation.mal)$corBeta
r.v.mutation.mal <- format(r.v.mutation.mal[2,1])
r.v.mutation.mal <-signif(as.numeric(r.v.mutation.mal)^2, digits= 2)
ld.v.mutation.mal<- summary(mutation.mal)$modelStruct$corStruct
ld.v.mutation.mal <- signif(ld.v.mutation.mal[1], digits = 2)
p.v.mutation.mal<-summary(mutation.mal)$tTable
p.v.mutation.mal<-signif(p.v.mutation.mal[2,4], digits = 2)
```

```{r}



mutation.mal<-ggplot(Data, aes(y=MalignancyPrevalence*100, x=log10(Mean.mutation.rate..SBS.genome.year.)))+
  ## I *think* that we only have mutation for Mammalia so you may need to change the line below
  scale_color_manual(values = c("Mammalia" = "#631879FF"))+
  scale_y_continuous(
    limits = c(0,75),
    breaks = c(0, 25,50,75),
    labels = c(0, 25,50,75))+
  geom_abline(intercept = coef(mutation.mal)[1]*100, slope =  coef(mutation.mal)[2]*100,
              color = 'grey',size = 1.2) +
  theme_cowplot(12)+
  theme(axis.title = element_text(size = 18))+
  ylab("Malignancy Prevalence (%)") +
  xlab("(log10) Mutation Rate") +
  geom_point(aes(colour= Clade, size = RecordsWithDenominators)) +
  scale_size(name   = "Total Necropsies",
             breaks = c(20,100,200,300,477),
             labels =  c(20,100,200,300,477))+
  geom_text_repel(aes(label=ifelse( MalignancyPrevalence > 0,as.character(common_name),'')),max.overlaps = Inf,size=5, direction = "y")+
  guides(colour = guide_legend(override.aes = list(size=3))) +
  labs(title = "Malignancy vs. Mutation Rate")+
  theme(
    plot.title = element_text(size = 20, face = "bold")) +
  theme(legend.position = "bottom")+
  labs(colour="Clade", size="Total Necropsies")
mutation.mal
##this line will save the graph to the folder you are using as your working directory
ggsave(filename='mutation.mal.pdf', width=9.5, height=7, limitsize=FALSE,bg="white")
```





