---
title: "Different Tree Test"
author: "Walker M"
date: "2024-04-10"
output: html_document
---

```{r}
library(nlme)
library(rms)
library(phytools)
library(geiger)
library(caper)
library(tidyverse)
library(cowplot)
library(ggrepel)
library(ggsci)
#make sure to run all of this before you get to work.
#pgls sey base (just run all of this)
modPgls.SEy = function (model, data, corClass = corBrownian, tree, se = NULL, 
                        method = c("REML", "ML"), interval = c(0, 1000), corClassValue=1, sig2e=NULL, ...) 
{
  Call <- match.call()
  corfunc <- corClass
  spp <- rownames(data)
  data <- cbind(data, spp)
  if (is.null(se)) 
    se <- setNames(rep(0, Ntip(tree)), tree$tip.label)[spp]
  else se <- se[spp]
  
  lk <- function(sig2e, data, tree, model, ve, corfunc, spp) {
    tree$edge.length <- tree$edge.length * sig2e
    ii <- sapply(1:Ntip(tree), function(x, e) which(e == 
                                                      x), e = tree$edge[, 2])
    tree$edge.length[ii] <- tree$edge.length[ii] + ve[tree$tip.label]
    vf <- diag(vcv(tree))[spp]
    w <- varFixed(~vf)
    COR <- corfunc(corClassValue, tree, form = ~spp, ...)
    fit <- gls(model, data = cbind(data, vf), correlation = COR, 
               method = method, weights = w)
    -logLik(fit)
  }
  
  if (is.null(sig2e)) {
    fit <- optimize(lk, interval = interval, data = data, tree = tree, 
                    model = model, ve = se^2, corfunc = corfunc, spp = spp)
    sig2e=fit$minimum
  }
  
  tree$edge.length <- tree$edge.length * sig2e
  ii <- sapply(1:Ntip(tree), function(x, e) which(e == x), 
               e = tree$edge[, 2])
  tree$edge.length[ii] <- tree$edge.length[ii] + se[tree$tip.label]^2
  vf <- diag(vcv(tree))[spp]
  w <- varFixed(~vf)
  obj <- gls(model, data = cbind(data, vf), correlation = corfunc(corClassValue, 
                                                                  tree, form = ~spp, ...), weights = w, method = method)
  obj$call <- Call
  obj$sig2e <- sig2e
  obj
}

#Internal function
pglsSEyPagelToOptimizeLambda=function(lambda,model,data,tree,...) {
  -logLik(modPgls.SEy(model=model,data=data,tree=tree,corClassValue=lambda,corClass=corPagel,fixed=T,...)) #Returns -logLikelihood of the pgls.SEy model with lambda fixed to the value of the lambda argument. sig2e will be optimized within modPgls.SEy unless given as an argument here
}

#Function intended for users
pglsSEyPagel=function(model, data, tree, lambdaInterval=c(0,1),...){
  optimizedModel=optimize(pglsSEyPagelToOptimizeLambda,lambdaInterval,model=model,data=data,tree=tree,...) #Optimizes lambda in the lambdaInterval using the pglsSEyPagelToOptimizeLambda function
  return(modPgls.SEy(model=model,data=data,tree=tree,corClass=corPagel,fixed=T,corClassValue=optimizedModel$minimum,...)) #Returns the final model fit
}

```


```{r}
#read data
Data <- read.csv("min1LH.csv")
Data<- filter(Data, is.element(Class, c("Mammalia")))

```


Bull Mammalia Tree
```{r}
#cutData <- Data[,c(5,9,10,11,13,38,42),drop=FALSE] 
cutData <- Data[,c(5,13,9,27,38),drop=FALSE] 
cutData[cutData < 0] <-NA
cutData <- na.omit(cutData)
tree <- read.tree("Mammaltree.newick")

cutData$Species <- gsub(" ", "_", cutData$Species) 
includedSpecies<-cutData$Species
pruned.tree<-drop.tip(
  tree, setdiff(
    tree$tip.label, includedSpecies))
pruned.tree <- keep.tip(pruned.tree,pruned.tree$tip.label)
cutData$Keep <- cutData$Species %in% pruned.tree$tip.label
cutData <- cutData[!(cutData$Keep==FALSE),]
rownames(cutData)<-cutData$Species
SE<-setNames(cutData$SE_simple,cutData$Species)[rownames(cutData)]
view(cutData)

adult.weight.neoBull<-pglsSEyPagel(NeoplasiaPrevalence~log10(adult_weight),data=cutData,tree=pruned.tree,se=SE,method = "ML")

summary(adult.weight.neoBull) 

#grab r squared, p value, and lambda from summary 

r.v.adult.weight.neoBull <- summary(adult.weight.neoBull)$corBeta
r.v.adult.weight.neoBull <- format(r.v.adult.weight.neoBull[2,1])
r.v.adult.weight.neoBull <-signif(as.numeric(r.v.adult.weight.neoBull)^2, digits= 2)
ld.v.adult.weight.neoBull<- summary(adult.weight.neoBull)$modelStruct$corStruct
ld.v.adult.weight.neoBull <- signif(ld.v.adult.weight.neoBull[1], digits = 2)
p.v.adult.weight.neoBull<-summary(adult.weight.neoBull)$tTable
p.v.adult.weight.neoBull<-signif(p.v.adult.weight.neoBull[2,4], digits = 2)
```

Our Data; Our Tree
```{r}

#adult weight models
#adult weight neo

cutData <- cutData
cutData[cutData < 0] <-NA
cutData <- na.omit(cutData)
tree <- read.tree("min20Fixed516.nwk")

cutData$Species <- gsub(" ", "_", cutData$Species) 
#cutData$common_name<-gsub("_", "", cutData$common_name)
includedSpecies<-cutData$Species
pruned.tree<-drop.tip(
  tree, setdiff(
    tree$tip.label, includedSpecies))
pruned.tree <- keep.tip(pruned.tree,pruned.tree$tip.label)
cutData$Keep <- cutData$Species %in% pruned.tree$tip.label
cutData <- cutData[!(cutData$Keep==FALSE),]
rownames(cutData)<-cutData$Species
SE<-setNames(cutData$SE_simple,cutData$Species)[rownames(cutData)]
view(cutData)

adult.weight.neo<-pglsSEyPagel(NeoplasiaPrevalence~log10(adult_weight),data=cutData,tree=pruned.tree,se=SE,method = "ML")

summary(adult.weight.neo) 

#grab r squared, p value, and lambda from summary 

r.v.adult.weight.neo <- summary(adult.weight.neo)$corBeta
r.v.adult.weight.neo <- format(r.v.adult.weight.neo[2,1])
r.v.adult.weight.neo <-signif(as.numeric(r.v.adult.weight.neo)^2, digits= 2)
ld.v.adult.weight.neo<- summary(adult.weight.neo)$modelStruct$corStruct
ld.v.adult.weight.neo <- signif(ld.v.adult.weight.neo[1], digits = 2)
p.v.adult.weight.neo<-summary(adult.weight.neo)$tTable
p.v.adult.weight.neo<-signif(p.v.adult.weight.neo[2,4], digits = 2)

```

```{r}
results <- data.frame(iteration = integer(100),
                      r_squared = numeric(100),
                      p_value = numeric(100),
                      lambda = numeric(100),
                      slope = numeric(100))

for(i in 1:1000) {
  # Adjust branch lengths - each branch gets a random factor between 0.5 and 1.5
  factors <- runif(length(pruned.tree$edge.length), 0.2, 5)
  adjusted.tree <- pruned.tree
  adjusted.tree$edge.length <- adjusted.tree$edge.length * factors
  
  # Run PGLS with adjusted tree
  pgls.model <- pglsSEyPagel(NeoplasiaPrevalence ~ log10(adult_weight), data = cutData, tree = adjusted.tree, se = SE, method = "ML")
  
  # Extract model outcomes
  r_squared <- signif(as.numeric(format(summary(pgls.model)$corBeta[2,1]))^2, digits= 2)
  lambda <- signif(summary(pgls.model)$modelStruct$corStruct[1], digits = 2)
  p_value <- signif(summary(pgls.model)$tTable[2,4], digits = 2)
  slope <-coef(pgls.model)[2]
  
  # Store results
  results[i,] <- c(i, r_squared, p_value, lambda,slope)
}

sdSlope<-sd(results$slope)

rangeSlope<-max(results$slope)-min(results$slope)

meanSlope<-mean(results$slope)

negSlope<-nrow(filter(results, slope < 0))

sdp_value<-sd(results$p_value)

rangep_value<-max(results$p_value)-min(results$p_value)

meanp_value<-mean(results$p_value)

negp_value<-nrow(filter(results, p_value <= 0.05))


summaryDF<-data.frame(sdofSlope =sdSlope, rangeofSlope =rangeSlope, meanofSlope = meanSlope, numSlopeNeg = negSlope, sdPvalue= sdp_value, pvalRange= rangep_value, pval_mean = meanp_value, signifP= negp_value )



```


